# Generated by Django 3.2.9 on 2021-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['chapter', 'verse']},
        ),
        migrations.AddField(
            model_name='verse',
            name='verse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
