# Generated by Django 3.2.9 on 2021-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
