# Generated by Django 3.2.9 on 2021-11-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0004_book_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('chapter', models.IntegerField()),
            ],
            options={
                'ordering': ['chapter'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['position']},
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versey.book'),
        ),
    ]
