# Generated by Django 3.2.9 on 2021-11-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0005_auto_20211126_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['book', 'chapter']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.TextField(),
        ),
    ]
