# Generated by Django 3.2.9 on 2021-11-30 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0006_auto_20211130_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versey.book'),
        ),
    ]
