# Generated by Django 3.2.9 on 2021-11-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versey', '0007_alter_chapter_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(max_length=100),
        ),
    ]
